#spring.application.name=cosmeticShop
server:
  port: 9000 # 학교 와이파이 8080 포트 블락으로 인해 이 부분 + vite.config.js 에서 target 변경
  #  port: 8080
  servlet:
    session:
      cookie:
        same-site: None # 로컬환경에서 크로스-포트 요청에 쿠키를 포함할 수 있음

spring:
  datasource:
        url: jdbc:mysql://localhost:3306/cosmall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1112

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update   # 실서버에서는 validate로 설정해야 한다
#      ddl-auto: create

  jwt: # 서버 띄울때는 이 비밀키도 .env 에 넣고 파라미터로 가져와야할듯 (보안이슈)
    secretKey: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    refreshExpirationMs: 604800000   # 7일(밀리초)