server:
  port: 9000
  servlet:
    session:
      cookie:
        same-site: None # 로컬환경에서 크로스-포트 요청에 쿠키를 포함할 수 있음
#        secure: true

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
        url: jdbc:mysql://localhost:3306/cosmall?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: dragonwaterr
        password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: dragonwaterr00@gmail.com
    password: ${GOOGLE_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

#  만약 PUT/PATCH 메소드가 안먹힌다면 주석 풀기
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update   # 실서버에서는 validate로
#      ddl-auto: create

  jwt: # 서버 띄울때는 비밀키 .env 에 넣고
    secretKey: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    refreshExpirationMs: 604800000   # 7일(밀리초)

#iamport
iamport:
  api:
    key: 8137003561175738  # 포트원 대시보드에서 발급받은 REST API Key
    secret: SM98tekCc1d28JEraNGtOGUYfnpiD01hOvhLTOEMTJOkIxruvToeLBOcYhrlhnUhJ4gnFezZhHttp1UZ # 포트원 REST API Secret
  code: imp86215134


