module.exports = {
    content: [
        "./src/**/*.{html,js,ts,jsx,tsx}",
        "app/**/*.{ts,tsx}",
        "components/**/*.{ts,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "blue-100": "var(--blue-100)",
                "blue-800": "var(--blue-800)",
                "cool-gray050": "var(--cool-gray050)",
                "cool-gray100": "var(--cool-gray100)",
                "cool-gray200": "var(--cool-gray200)",
                "cool-gray50": "var(--cool-gray50)",
                "cool-gray500": "var(--cool-gray500)",
                "cool-gray600": "var(--cool-gray600)",
                "cool-gray900": "var(--cool-gray900)",
                "gray-500": "var(--gray-500)",
                "green-100": "var(--green-100)",
                "green-500": "var(--green-500)",
                "green-800": "var(--green-800)",
                "red-200": "var(--red-200)",
                "red-800": "var(--red-800)",
                white: "var(--white)",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            fontFamily: {
                "text-base-font-medium": "var(--text-base-font-medium-font-family)",
                "text-base-font-normal": "var(--text-base-font-normal-font-family)",
                "text-base-font-semibold": "var(--text-base-font-semibold-font-family)",
                "text-sm-font-normal": "var(--text-sm-font-normal-font-family)",
                "text-sm-font-semibold": "var(--text-sm-font-semibold-font-family)",
                "text-xl-font-bold": "var(--text-xl-font-bold-font-family)",
                "text-xl-font-semibold": "var(--text-xl-font-semibold-font-family)",
                "text-xs-font-medium": "var(--text-xs-font-medium-font-family)",
                "text-xs-font-normal": "var(--text-xs-font-normal-font-family)",
                "text-xs-font-semibold": "var(--text-xs-font-semibold-font-family)",
                sans: [
                    "ui-sans-serif",
                    "system-ui",
                    "sans-serif",
                    '"Apple Color Emoji"',
                    '"Segoe UI Emoji"',
                    '"Segoe UI Symbol"',
                    '"Noto Color Emoji"',
                ],
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
        container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    },
    plugins: [],
    darkMode: ["class"],
};
